// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


DataFrame prepare_calculate_metrics(DataFrame network_table, DataFrame ground_truth);
RcppExport SEXP _multiCSN_prepare_calculate_metrics(SEXP network_tableSEXP, SEXP ground_truthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type network_table(network_tableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type ground_truth(ground_truthSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_calculate_metrics(network_table, ground_truth));
    return rcpp_result_gen;
END_RCPP
}

List prepare_metric_vectors(DataFrame network_table, DataFrame ground_truth);
RcppExport SEXP _multiCSN_prepare_metric_vectors(SEXP network_tableSEXP, SEXP ground_truthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type network_table(network_tableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type ground_truth(ground_truthSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_metric_vectors(network_table, ground_truth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiCSN_prepare_calculate_metrics", (DL_FUNC) &_multiCSN_prepare_calculate_metrics, 2},
    {"_multiCSN_prepare_metric_vectors", (DL_FUNC) &_multiCSN_prepare_metric_vectors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiCSN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
