# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prepare_calculate_metrics <- function(network_table, ground_truth) {
    .Call(`_multiCSN_prepare_calculate_metrics`, network_table, ground_truth)
}

prepare_metric_vectors <- function(network_table, ground_truth) {
    .Call(`_multiCSN_prepare_metric_vectors`, network_table, ground_truth)
}

